services:
  - type: web
    name: batheja-garments-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Yugam:Yugam006@cluster0.5dogq5t.mongodb.net/clothing-store?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: batheja_super_secret_key_2026
      - key: PORT
        value: 5000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: PAYMENT_MODE
        value: live
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false


